#!/bin/sh /etc/rc.common

START=91

start() {
    if [ ! -f "/usr/sbin/uu/uuplugin_monitor.sh" ]; then
        wget http://uu.gdl.netease.com/uuplugin-script/202010221713/install.sh -O install.sh
        /bin/sh install.sh openwrt $(uname -m)
        rm install.sh
    fi
}
